### ISSUE TITLE
Numeric comparison without considering type?

### ISSUE THREAD

**Issue by bt** [gotestyourself/gotest.tools#119]
Can't seem to find any docs mentioning this but is there a way I can do a numeric check without considering type?

This is useful for situations where I'm testing for zero and my tests are failing. For example, I do something like this:

```
var res map[string]interface{}
err := json.Unmarshal([]byte(body), &res)
assert.NilError(t, err)

assert.Equal(t, res["count"], 0)
```

Gives me the following fail message:

```
assertion failed: 0 (res["count"] float64) != 0 (int)
```

**Comment by dnephin** [comment]
Excellent question!

There is no way to ignore the type, this is by design. Any code that calls the unit under test will need to be aware of the type, so the test should be as well.

To handle mismatched types my recommendation is to cast the expected value to the type you expect. Using your example that would look like:

```go
assert.Equal(t, res["count"], float64(0))
```

**Comment by bt** [comment]
Ah okay that works.

Guess my brain wasn't working today, I did the opposite instead 😂:

```
assert.Equal(t, int(res["count"].(float64)), 0)
```

LOL! Thanks for the reply though! 😁
