### ISSUE TITLE
assert.Equal, assert.DeepEqual: maybe "code style" bug, easy code improvement

### ISSUE THREAD

**Issue by Sieciechu** [gotestyourself/gotest.tools#182]
## Intro.
As a developer using your (very nice) library and assert.Equal, and assert.DeepEqual I would like to be able to distinguish which value is actual, which is expected more easily.

## Details.
Why? When we read:
`assert.Equal(t, 1, list.Count())`, or 
`assert.Equal(t, list.Count(), 1)`
and we get error, we see message "assertion failed: 2 (int) != 1 (int)". And question: we know that they must be equal, but how do we know which one of these values is incorrect? Or asking otherwise: which of these values is actual and which is expected?
- Passed parameters `1`, `list.Count()` do not tell us which value is actual and which is expected
- By reading the error message - "assertion failed: 2 (int) != 1 (int)" - we don't know which value is actual and which is expected.
- By reading the method interface `func Equal(t TestingT, x, y interface{}, msgAndArgs ...interface{}) {` - "x, y interface{}" (https://github.com/gotestyourself/gotest.tools/blob/master/assert/assert.go#L264) -  also we cannot distinguish which is actual and which is expected
- Yes, we can write something like `assert.Equal(t, list.Count(), 1, "Expected count 1")` , but writing such in every assert.Equal, in every test, leads to a boilerplate code
- the doc says "If the comparison fails Equal will use variable names for x and y as part of the failure message to identify the actual and expected values" (https://github.com/gotestyourself/gotest.tools/blob/master/assert/assert.go#L255) - so yes, we can use variables like `expectedCount`, `actualCount` to see the names in the assert error message, but many times we do not write the code, but rather read the code which has/had been committed by other devs, and they could write in similar manner like shown in the top. And also if we would have to always assign values to such variables before every assert it could lead to boilerplate code.

## Proposition.
Therefore my proposition is simple very easy - to change parameter names to more meaningful, for example:
`func Equal(t TestingT, actual, expected interface{}, msgAndArgs ...interface{}) {`
And then we can quite easily know which value is actual and which is expected.

Similar practice is done in other popular testing frameworks, i.e.:
- java junit: https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertArrayEquals-double:A-double:A-
- node.js : https://nodejs.org/api/assert.html#assert_assert_strictequal_actual_expected_message
- php phpunit: https://phpunit.readthedocs.io/en/8.5/assertions.html#assertequals

Hmm, such change though easy to implement, in practice it would be the change of package's public API/interface, so if you would agree on it, it should rather be released with some major release. And if you agree on it I prepared very easy pull request as a proposition: https://github.com/gotestyourself/gotest.tools/pull/183 .
And of course - if you have better/more appropriate solution, then of course it will be better :) .

**Comment by dnephin** [comment]
Thank you for the thorough write-up and explanation of the problem! I think this is indeed a challenging problem. When I was working on `Equal` and `DeepEqual` I considered this problem. At the time most of the test suites I was looking at were using `stretchr/testify`, which does use the order `expected, actual`.

I see that in the examples you link 2 of them use `expected, actual`, and the third uses `actual, expected`. In my opinion the order should always be `actual, expected`. For one because I personally feel that reads better, but primarily because other assertions (Error, Contains, Len, etc) all put the expected value second. The inconsistency of Equal putting it first is not good.

Despite my strong preference for the `actual, expected` order, I decided to make `assert`arg order agnostic. 

The reason is that because there is no convention, many test authors will do what feels natural to them. While I was looking at the `testify/assert` usage I noticed that within many code bases both orders were used, even though the function signature suggested a specific order. I suspect that even if we were to change the variable names and failure messages we'd see just as many assertions using the wrong order.

This problem can be addressed in code review, but it seems to me that "use a variable for expected", or "add additional context to the failure message with `formatAndArgs`" is just as easy to enforce during code review without making a library change.

Given the difficulty to enforce the order I am very hesitant to make a breaking change to address the problem. But I am still interested in improving the situation.

I know some libraries use a style like this `Expect(actual).ToBe(expected)`. This definitely addresses the problem, but I find the style a little less practical to use.

Another option might be to introduce new functions like:
```go
EqualTo(t, actual, expected)
```
I'm also weary of introducing more aliases for the same functionality so would prefer to not take that option.

I wonder if the problem could be addressed with a linter? It could look at all the `assert.Equal` calls in   a project and report on any that don't use variables for at least one of the values, and report something like "assertion may produce ambiguous failure messages". 

I think using a single variable (or function call) would be enough, because as long as one of the variables is marked as expected or actual, you know what the other one is.

Projects which want to solve the problem could even add a local function like:

```go
func expected(x interface{}) interface{} {
    return x
}
```

That would allow them to mark the expected value in the test:

```go
assert.Equal(t, something, expected(10))
```

The linter could even accept a custom error message, to inform the user of the right function to use.

**Comment by Sieciechu** [comment]
Thank you very much for your the very deep, precise explanation! Regarding the
> within many code bases both orders were used, even though the function signature suggested a specific order.

oo, that's surprising, just wonder does it happen more often because of accidents or laziness:). Anyway keeping in mind current situation, that plenty of projects **already** use your library very freedomly, it's not something to crash/fight hard for. I can just agree with your reasons. I wish I could propose you some smart solution for it, but I don't see any.

Once again thank you very much for your the very deep, precise explanation! Best regards! :)
