### ISSUE TITLE
Package defines -update flag even if golden package is unused

### ISSUE THREAD

**Issue by tadeokondrak** [gotestyourself/gotest.tools#270]
We use `gotest.tools/v3/assert` right now and I'm happy with it. 

I'd like to use `github.com/hexops/autogold` to automatically update tests with inline values, but if I try to use it and `gotest.tools/v3/assert` in the same package, initialization panics with `flag redefined: update` and tests don't run.

I'd understand that the problem might be impossible to fix if I were using both `gotest.tools/v3/golden` and `autogold`, but it feels like it should be possible to use `gotest.tools/v3/assert` and `autogold` together.

Would you be interested in a PR to fix this? Maybe the internal packages can be rearranged to only define the flag when `golden` is used.

**Comment by dnephin** [comment]
Thank you for the bug report! I have been wondering if this flag would conflict at some point.

The reasons it's imported from `/v3/assert` is because `assert.Equal` has `autogold` style behaviour for string values. As long as the expected variable is named `expected` or `expected<Something>` that value can be updated with `-update`.

I might you might be using `autogold` for non-string values as well though.

I've got an idea for how to fix this using https://pkg.go.dev/flag#Lookup. Let me open a PR to see how it works.

**Comment by dnephin** [comment]
I've opened #271. I tried it out , and it works as long as `gotest.tools/v3` is imported after `autogold`. If `autogold` implements the same logic, then the import order won't matter.

Let me know if this works for you.

**Comment by tadeokondrak** [comment]
Great, thanks! I'll take a look at getting `autogold` to do the same thing.

**Comment by tadeokondrak** [comment]
With both packages patched everything works great. In my case autogold is imported second so #271 isn't actually being used yet, but it's good not to rely on import order.
